FROM golang:1.18.10 as build
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM build as pakage_build
WORKDIR /pkg
COPY --from=fabricioveronez/pacote-bin:v1 /pkg/pacote.bin .


FROM alpine:3.18.4 as pp
WORKDIR /app
COPY --from=pakage_build /pkg/pacote.bin  .
COPY --from=pakage_build /build/main .
CMD ["./main"]