services: 
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_TAG:-latest}   # -latest optional
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    profiles:
      - dev 
      - homolo
    volumes:      
      - postgres_docker_vol:/var/lib/postgresql/data
    networks:
      - kubenews_net